# Copyright Yury Korotovskikh 2022 <u.korotovskiy@nil.foundation>

name: Test

on:
  # Triggers the workflow on pull request
  pull_request:
  # Allows to trigger workflow manually
  workflow_dispatch:

jobs:
  test:
    runs-on: [ubuntu-latest]
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run : npm ci --ignore-scripts

      - name: Lint
        run: npm run lint

      - name: Lint:editorconfig
        run: npm run lint:editorconfig

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
